### ISSUE TITLE
Leverage Laravel JSON/Array Casts

### ISSUE THREAD

**Issue by aleemb** [appstract/laravel-meta#3]
As per https://laravel.com/docs/5.4/eloquent-mutators#array-and-json-casting which would make the custom json mutators in the current model obsolete.

**Comment by gizburdt** [comment]
I am aware of the casts, but meta can also be stored as a string. When using an array cast it will return an array, even if the meta is a string. That wouldn't be very nice..

**Comment by gizburdt** [comment]
OK, I was wrong, strings a just saves as strings.. Maybe array in not the right name for the cast

**Comment by gizburdt** [comment]
Thank you :) https://github.com/appstract/laravel-meta/commit/89dadd3c094af10d9a7d66c577fc0f2609ac662f
